CREATE TABLE SPONSOR (
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(25),
    EMAIL VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE MARKETPLACE (
    ID VARCHAR(10) NOT NULL,
    SPONSOR VARCHAR(30),
    PRIMARY KEY (ID)
);

CREATE TABLE ADMINISTRATIVE (
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(25),
    EMAIL VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE DRIVER (
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(25),
    EMAIL VARCHAR(50),
    ORDER_HISTORY VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE SPONSORED_BY (
    SPONSOR VARCHAR(10) NOT NULL,
    DRIVER VARCHAR(10) NOT NULL,
    POINT_TOTAL INTEGER(4),
    PRIMARY KEY (SPONSOR, DRIVER),
    FOREIGN KEY (SPONSOR) REFERENCES SPONSOR(ID),
    FOREIGN KEY (DRIVER) REFERENCES DRIVER(ID)
);

CREATE TABLE CAN_VIEW (
    SPONSOR VARCHAR(10) NOT NULL,
    DRIVER VARCHAR(10) NOT NULL,
    MARKET VARCHAR(10) NOT NULL,
    PRIMARY KEY (SPONSOR, DRIVER, MARKET),
    FOREIGN KEY (SPONSOR) REFERENCES SPONSOR(ID),
    FOREIGN KEY (MARKET) REFERENCES MARKETPLACE(ID),
    FOREIGN KEY (DRIVER) REFERENCES DRIVER(ID)
);

CREATE TABLE CAN_MODIFY_SPONSOR (
    ADMIN VARCHAR(10) NOT NULL,
    SPONSOR VARCHAR(10) NOT NULL,
    PRIMARY KEY (ADMIN, SPONSOR),
    FOREIGN KEY (SPONSOR) REFERENCES SPONSOR(ID),
    FOREIGN KEY (ADMIN) REFERENCES ADMINISTRATIVE(ID)
);

CREATE TABLE CAN_MODIFY_DRIVER (
    ADMIN VARCHAR(10) NOT NULL,
    DRIVER VARCHAR(10) NOT NULL,
    PRIMARY KEY (ADMIN, DRIVER),
    FOREIGN KEY (DRIVER) REFERENCES DRIVER(ID),
    FOREIGN KEY (ADMIN) REFERENCES ADMINISTRATIVE(ID)
);

CREATE TABLE CAN_MODIFY_MARKETPLACE (
    ADMIN VARCHAR(10) NOT NULL,
    MARKET VARCHAR(10) NOT NULL,
    PRIMARY KEY (ADMIN, MARKET),
    FOREIGN KEY (MARKET) REFERENCES MARKETPLACE(ID),
    FOREIGN KEY (ADMIN) REFERENCES ADMINISTRATIVE(ID)
);

CREATE TABLE ADD_PRODUCTS (
    MARKET VARCHAR(10) NOT NULL,
    SPONSOR VARCHAR(10) NOT NULL,
    PRODUCT_ID INTEGER(12) NOT NULL,
    PRIMARY KEY (MARKET, SPONSOR),
    FOREIGN KEY (MARKET) REFERENCES MARKETPLACE(ID),
    FOREIGN KEY (SPONSOR) REFERENCES SPONSOR(ID)
);

CREATE TABLE PRODUCT_LIST (
    SPONSOR VARCHAR(10) NOT NULL,
    PRODUCT_ID VARCHAR(15) NOT NULL
);

CREATE TABLE DRIVER_CART (
    ID INTEGER(15) NOT NULL AUTO_INCREMENT,
    DRIVER VARCHAR(10) NOT NULL,
    NAME VARCHAR(155) NOT NULL,
    PRICE INTEGER(15) NOT NULL,
    SPONSOR VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SPONSORED_BY (
    SPONSOR VARCHAR(10) NOT NULL,
    DRIVER VARCHAR(10) NOT NULL,
    POINT_TOTAL INTEGER(10)
);

CREATE TABLE ORDER_HISTORY(
    ID INTEGER(10) NOT NULL AUTO_INCREMENT,
    DRIVER VARCHAR(10) NOT NULL,
    SPONSOR VARCHAR(10) NOT NULL,
    ORDER_DATE VARCHAR(10) NOT NULL,
    NAME VARCHAR(155) NOT NULL,
    PRICE INTEGER(15) NOT NULL,
    PRIMARY KEY (ID)
);