INSERT INTO SPONSOR
VALUES ('S1', 'John Smith', 'jsmith1', 'SPONSORPASSWORD1', 'jsmith1@MAIL.COM');
INSERT INTO SPONSOR
VALUES ('S2', 'Andy Johnson', 'andyj2', 'SPONSORPASSWORD2', 'andyj2@MAIL.COM');
INSERT INTO SPONSOR
VALUES ('S3', 'Michael Scott', 'theoffice', 'SPONSORPASSWORD3', 'theoffice@MAIL.COM');
INSERT INTO SPONSOR
VALUES ('S4', 'Fred Thompson', 'fthompson4', 'SPONSORPASSWORD4', 'fthompson4@MAIL.COM');
INSERT INTO SPONSOR
VALUES ('S5', 'Austin Rivers', 'arivers5', 'SPONSORPASSWORD5', 'arivers5@MAIL.COM');

SELECT * FROM SPONSOR;
SELECT * FROM SPONSOR WHERE NAME = 'Andy Johnson';

INSERT INTO MARKETPLACE
VALUES ('M1', 'S1');
INSERT INTO MARKETPLACE
VALUES ('M2', 'S2');
INSERT INTO MARKETPLACE
VALUES ('M3', 'S3');
INSERT INTO MARKETPLACE
VALUES ('M4', 'S4');
INSERT INTO MARKETPLACE
VALUES ('M5', 'S5');

SELECT * FROM MARKETPLACE;
SELECT * FROM MARKETPLACE WHERE SPONSOR = 'S2';

INSERT INTO ADMINISTRATIVE
VALUES ('A1', 'James Earl', 'jearl1', 'ADMINPASSWORD1', 'jearl1@EMAIL.COM');
INSERT INTO ADMINISTRATIVE
VALUES ('A2', 'Steven Powers', 'stevenp2', 'ADMINPASSWORD2', 'stevenp2@EMAIL.COM');
INSERT INTO ADMINISTRATIVE
VALUES ('A3', 'Tom Brady', 'tb12', 'ADMINPASSWORD3', '6rings@EMAIL.COM');
INSERT INTO ADMINISTRATIVE
VALUES ('A4', 'Aaron Rodgers', 'thegoatrodgers', 'ADMINPASSWORD4', 'packers@EMAIL.COM');
INSERT INTO ADMINISTRATIVE
VALUES ('A5', 'Kirk Cousins', 'captaink', 'ADMINPASSWORD5', 'captaink@EMAIL.COM');

SELECT * FROM ADMINISTRATIVE;
SELECT * FROM ADMINISTRATIVE WHERE NAME = 'FIRST2';

INSERT INTO DRIVER
VALUES ('D1', 'Cam Newton', 'scamnewton1', 'DRIVERPASSWORD1', 'scamnewton1@EMAIL.COM', 'DRIVERORDERHISTORY1');
INSERT INTO DRIVER
VALUES ('D2', 'Matt Ryan', 'falcons283', 'DRIVERPASSWORD2', 'falcons283@EMAIL.COM', 'DRIVERORDERHISTORY2');
INSERT INTO DRIVER
VALUES ('D3', 'Drew Brees', 'drewbweez', 'DRIVERPASSWORD3', 'drewbweez@EMAIL.COM', 'DRIVERORDERHISTORY3');
INSERT INTO DRIVER
VALUES ('D4', 'Teddy Bridgewater', 'imaprettygoodbackup', 'DRIVERPASSWORD4', 'teddyb@EMAIL.COM', 'DRIVERORDERHISTORY4');
INSERT INTO DRIVER
VALUES ('D5', 'Baker Mayfield', 'johnnymanziel2', 'DRIVERPASSWORD5', 'bakerOU@EMAIL.COM', 'DRIVERORDERHISTORY5');

SELECT * FROM DRIVER;
SELECT * FROM DRIVER WHERE NAME = 'DRIVER2';

INSERT INTO SPONSORED_BY
VALUES ('S1', 'D1', 101);
INSERT INTO SPONSORED_BY
VALUES ('S2', 'D1', 102);
INSERT INTO SPONSORED_BY
VALUES ('S3', 'D1', 103);
INSERT INTO SPONSORED_BY
VALUES ('S1', 'D2', 201);
INSERT INTO SPONSORED_BY
VALUES ('S2', 'D2', 202);
INSERT INTO SPONSORED_BY
VALUES ('S3', 'D2', 203);
INSERT INTO SPONSORED_BY
VALUES ('S1', 'D3', 301);
INSERT INTO SPONSORED_BY
VALUES ('S2', 'D3', 302);
INSERT INTO SPONSORED_BY
VALUES ('S1', 'D4', 401);

INSERT INTO CAN_MODIFY_SPONSOR
VALUES ('A1', 'S1');
INSERT INTO CAN_MODIFY_SPONSOR
VALUES ('A2', 'S2');
INSERT INTO CAN_MODIFY_SPONSOR
VALUES ('A3', 'S3');
INSERT INTO CAN_MODIFY_SPONSOR
VALUES ('A4', 'S4');
INSERT INTO CAN_MODIFY_SPONSOR
VALUES ('A5', 'S5');

SELECT * FROM CAN_MODIFY_SPONSOR;
SELECT * FROM CAN_MODIFY_SPONSOR WHERE SPONSOR_ID = 'S2';

INSERT INTO CAN_MODIFY_DRIVER
VALUES ('A1', 'D1');
INSERT INTO CAN_MODIFY_DRIVER
VALUES ('A2', 'D2');
INSERT INTO CAN_MODIFY_DRIVER
VALUES ('A3', 'D3');
INSERT INTO CAN_MODIFY_DRIVER
VALUES ('A4', 'D4');
INSERT INTO CAN_MODIFY_DRIVER
VALUES ('A5', 'D5');

SELECT * FROM CAN_MODIFY_DRIVER;
SELECT * FROM CAN_MODIFY_DRIVER WHERE SSN = 'D2';

INSERT INTO CAN_MODIFY_MARKETPLACE
VALUES ('A1', 'M1');
INSERT INTO CAN_MODIFY_MARKETPLACE
VALUES ('A2', 'M2');
INSERT INTO CAN_MODIFY_MARKETPLACE
VALUES ('A3', 'M3');
INSERT INTO CAN_MODIFY_MARKETPLACE
VALUES ('A4', 'M4');
INSERT INTO CAN_MODIFY_MARKETPLACE
VALUES ('A5', 'M5');

SELECT * FROM CAN_MODIFY_MARKETPLACE;
SELECT * FROM CAN_MODIFY_MARKETPLACE WHERE MARKET_ID = 'M2';

INSERT INTO ADD_PRODUCTS
VALUES ('M1', 'S1', 123456789012);
INSERT INTO ADD_PRODUCTS
VALUES ('M2', 'S2', 234567890123);
INSERT INTO ADD_PRODUCTS
VALUES ('M3', 'S3', 345678901234);
INSERT INTO ADD_PRODUCTS
VALUES ('M4', 'S4', 456789012345);
INSERT INTO ADD_PRODUCTS
VALUES ('M5', 'S5', 567890123456);
INSERT INTO ADD_PRODUCTS
VALUES ('M1', 'S1', 678901234567);
INSERT INTO ADD_PRODUCTS
VALUES ('M2', 'S2', 789012345678);
INSERT INTO ADD_PRODUCTS
VALUES ('M3', 'S3', 890123456789);
INSERT INTO ADD_PRODUCTS
VALUES ('M4', 'S4', 901234567890);
INSERT INTO ADD_PRODUCTS
VALUES ('M5', 'S5', 012345678901);

INSERT INTO PRODUCT_LIST
VALUES ('S1', '202807211458');
INSERT INTO PRODUCT_LIST
VALUES ('S1', '264123730971');
INSERT INTO PRODUCT_LIST
VALUES ('S1', '264378312775');
INSERT INTO PRODUCT_LIST
VALUES ('S1', '133055512686');
INSERT INTO PRODUCT_LIST
VALUES ('S1', '133069230504');
INSERT INTO PRODUCT_LIST
VALUES ('S2', '153704459990');
INSERT INTO PRODUCT_LIST
VALUES ('S2', '392498425860');
INSERT INTO PRODUCT_LIST
VALUES ('S2', '223718209927');
INSERT INTO PRODUCT_LIST
VALUES ('S3', '254405553962');